local WindUI = (function()
    local url = "https://github.com/Footagesus/WindUI/releases/latest/download/main.lua"
    local raw = game:HttpGet(url)
    local patched = raw:gsub('IconLabelFrame = New%( "ImageLabel", %{', 'IconLabelFrame = New( "Frame", {')
    return loadstring(patched)()
end)()

local function DefineTheme(name, colors)
    WindUI:AddTheme({
        Name = name,
        Primary = colors.primary,
        White = colors.white,
        Black = colors.black,
        Dialog = colors.dialog,
        Background = colors.background,
        BackgroundTransparency = 0,
        Hover = colors.hover,
        PanelBackground = colors.panelBackground,
        PanelBackgroundTransparency = .95,
        WindowBackground = colors.windowBackground,
        WindowShadow = colors.windowShadow,
        WindowTopbarTitle = colors.windowTopbarTitle,
        WindowTopbarAuthor = colors.windowTopbarAuthor,
        WindowTopbarIcon = colors.windowTopbarIcon,
        WindowTopbarButtonIcon = colors.windowTopbarButtonIcon,
        WindowSearchBarBackground = colors.windowSearchBarBackground,
        TabBackground = colors.tabBackground,
        TabBackgroundHover = colors.tabBackgroundHover,
        TabBackgroundHoverTransparency = .97,
        TabBackgroundActive = colors.tabBackgroundActive,
        TabBackgroundActiveTransparency = 0.93,
        TabText = colors.tabText,
        TabTextTransparency = 0.3,
        TabTextTransparencyActive = 0,
        TabTitle = colors.tabTitle,
        TabIcon = colors.tabIcon,
        TabIconTransparency = 0.4,
        TabIconTransparencyActive = 0.1,
        TabBorderTransparency = 1,
        TabBorderTransparencyActive = 0.75,
        TabBorder = colors.tabBorder,
        ElementBackground = colors.elementBackground,
        ElementBackgroundTransparency = .93,
        ElementBackgroundHover = WindUI.Creator:AddColor("ElementBackground", "#ffffff", 1/10),
        ElementTitle = colors.elementTitle,
        ElementDesc = colors.elementDesc,
        ElementIcon = colors.elementIcon,
        PopupBackground = colors.popupBackground,
        PopupBackgroundTransparency = "BackgroundTransparency",
        PopupTitle = colors.popupTitle,
        PopupContent = colors.popupContent,
        PopupIcon = colors.popupIcon,
        DialogBackground = colors.dialogBackground,
        DialogBackgroundTransparency = "BackgroundTransparency",
        DialogTitle = colors.dialogTitle,
        DialogContent = colors.dialogContent,
        DialogIcon = colors.dialogIcon,
        Toggle = colors.toggle,
        ToggleBar = colors.toggleBar,
        Checkbox = colors.checkbox,
        CheckboxIcon = colors.checkboxIcon,
        CheckboxBorder = colors.checkboxBorder,
        CheckboxBorderTransparency = .75,
        SliderIcon = colors.sliderIcon,
        Slider = colors.slider,
        SliderThumb = colors.sliderThumb,
        SliderIconFrom = colors.sliderIconFrom,
        SliderIconTo = colors.sliderIconTo,
        Tooltip = colors.tooltip,
        TooltipText = colors.tooltipText,
        TooltipSecondary = colors.tooltipSecondary,
        TooltipSecondaryText = colors.tooltipSecondaryText,
        TabSectionIcon = colors.tabSectionIcon,
        SectionIcon = colors.sectionIcon,
        SectionExpandIcon = colors.sectionExpandIcon,
        SectionExpandIconTransparency = .4,
        SectionBox = colors.sectionBox,
        SectionBoxTransparency = .95,
        SectionBoxBorder = colors.sectionBoxBorder,
        SectionBoxBorderTransparency = .75,
        SectionBoxBackground = colors.sectionBoxBackground,
        SectionBoxBackgroundTransparency = .95,
        SearchBarBorder = colors.searchBarBorder,
        SearchBarBorderTransparency = .75,
        Notification = colors.notification,
        NotificationTitle = colors.notificationTitle,
        NotificationTitleTransparency = 0,
        NotificationContent = colors.notificationContent,
        NotificationContentTransparency = .4,
        NotificationDuration = colors.notificationDuration,
        NotificationDurationTransparency = .95,
        NotificationBorder = colors.notificationBorder,
        NotificationBorderTransparency = .75,
        DropdownTabBorder = colors.dropdownTabBorder,
        LabelBackground = colors.labelBackground,
        LabelBackgroundTransparency = .95,
    })
end

local function Hex(hex)
    return Color3.fromHex(hex)
end

local function RGB(r, g, b)
    return Color3.fromRGB(r, g, b)
end

DefineTheme("Bandit", {
    primary = Hex("#E8C84A"),
    white = RGB(255,255,255),
    black = RGB(0,0,0),
    dialog = Hex("#2a1a0a"),
    background = Hex("#2c1a0c"),
    hover = Hex("#f2d97a"),
    panelBackground = RGB(255,255,255),
    windowBackground = Hex("#2c1a0c"),
    windowShadow = RGB(0,0,0),
    windowTopbarTitle = Hex("#E8C84A"),
    windowTopbarAuthor = Hex("#f2d97a"),
    windowTopbarIcon = Hex("#E8C84A"),
    windowTopbarButtonIcon = Hex("#E8C84A"),
    windowSearchBarBackground = Hex("#3e281a"),
    tabBackground = Hex("#3e281a"),
    tabBackgroundHover = Hex("#4a3320"),
    tabBackgroundActive = Hex("#E8C84A"),
    tabText = Hex("#f5e6c8"),
    tabTitle = Hex("#E8C84A"),
    tabIcon = Hex("#E8C84A"),
    tabBorder = RGB(255,255,255),
    elementBackground = Hex("#3e281a"),
    elementTitle = Hex("#f5e6c8"),
    elementDesc = Hex("#e6c87a"),
    elementIcon = Hex("#E8C84A"),
    popupBackground = Hex("#2c1a0c"),
    popupTitle = Hex("#E8C84A"),
    popupContent = Hex("#f2d97a"),
    popupIcon = Hex("#E8C84A"),
    dialogBackground = Hex("#2c1a0c"),
    dialogTitle = Hex("#E8C84A"),
    dialogContent = Hex("#f2d97a"),
    dialogIcon = Hex("#E8C84A"),
    toggle = Hex("#B22222"),
    toggleBar = RGB(255,255,255),
    checkbox = Hex("#B22222"),
    checkboxIcon = RGB(255,255,255),
    checkboxBorder = RGB(255,255,255),
    sliderIcon = Hex("#B22222"),
    slider = Hex("#B22222"),
    sliderThumb = Hex("#E74C3C"),
    sliderIconFrom = Hex("#B22222"),
    sliderIconTo = Hex("#B22222"),
    tooltip = Hex("#3e281a"),
    tooltipText = RGB(255,255,255),
    tooltipSecondary = Hex("#E8C84A"),
    tooltipSecondaryText = RGB(255,255,255),
    tabSectionIcon = Hex("#E8C84A"),
    sectionIcon = Hex("#E8C84A"),
    sectionExpandIcon = RGB(255,255,255),
    sectionBox = RGB(255,255,255),
    sectionBoxBorder = RGB(255,255,255),
    sectionBoxBackground = RGB(255,255,255),
    searchBarBorder = RGB(255,255,255),
    notification = Hex("#2c1a0c"),
    notificationTitle = Hex("#E8C84A"),
    notificationContent = Hex("#f2d97a"),
    notificationDuration = RGB(255,255,255),
    notificationBorder = Hex("#B22222"),
    dropdownTabBorder = RGB(255,255,255),
    labelBackground = RGB(255,255,255),
})

WindUI:SetTheme("Bandit")

return WindUI